;;; iduh-org-mode-ssg.el --- Minimal Static Site Generator for Org-Mode -*- lexical-binding: t; -*-

;; Author: Generated by AI Assistant
;; Version: 1.0.0
;; Keywords: org, html, static-site-generator
;; Package-Requires: ((emacs "27.1"))

;;; Commentary:

;; A minimal static site generator that converts a stripped-down Org-Mode
;; document into a clean, styled HTML file.
;;
;; Supported Org-Mode features:
;; - #+TITLE: Document title
;; - #+SUBTITLE: Document subtitle
;; - * Heading (single level only, creates sections)
;; - Paragraph text
;; - [[image.png][alt text]] Image embedding (alt text mandatory)
;; - #+BEGIN_QUOTE ... #+END_QUOTE Text quoting
;; - *bold* /italic/ _underline_ +strikethrough+ inline formatting
;;
;; NOT supported (throws error):
;; - ** Sub-headings (or any deeper nesting)
;;
;; Usage:
;;   (iduh-org-mode-ssg-generate "input.org" "output.html" "style.css")
;;
;; Or interactively:
;;   M-x iduh-org-mode-ssg-generate-interactive

;;; Code:

(require 'cl-lib)

;;; ============================================================================
;;; Configuration
;;; ============================================================================

(defgroup iduh-org-mode-ssg nil
  "Minimal static site generator for Org-Mode."
  :group 'org
  :prefix "iduh-org-mode-ssg-")

(defcustom iduh-org-mode-ssg-default-lang "en"
  "Default language attribute for generated HTML."
  :type 'string
  :group 'iduh-org-mode-ssg)

(defcustom iduh-org-mode-ssg-google-fonts-url
  "https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=JetBrains+Mono:wght@400;500&family=Merriweather:ital,wght@0,400;1,400&family=Playfair+Display:wght@600;700&display=swap"
  "Google Fonts URL to include in generated HTML."
  :type 'string
  :group 'iduh-org-mode-ssg)

;;; ============================================================================
;;; Error Handling
;;; ============================================================================

(define-error 'iduh-org-mode-ssg-error "IDUH-Org-Mode-SSG Error")
(define-error 'iduh-org-mode-ssg-subheading-error "Sub-heading not allowed" 'iduh-org-mode-ssg-error)
(define-error 'iduh-org-mode-ssg-image-error "Image syntax error" 'iduh-org-mode-ssg-error)
(define-error 'iduh-org-mode-ssg-parse-error "Parse error" 'iduh-org-mode-ssg-error)

(defun iduh-org-mode-ssg--error (type message &rest args)
  "Signal an iduh-org-mode-ssg error of TYPE with MESSAGE formatted with ARGS."
  (signal type (list (apply #'format message args))))

;;; ============================================================================
;;; Parsing Functions
;;; ============================================================================

(defun iduh-org-mode-ssg--parse-file (filepath)
  "Parse an Org file at FILEPATH and return a structured document.
Returns a plist with :title, :subtitle, and :sections."
  (with-temp-buffer
    (insert-file-contents filepath)
    (iduh-org-mode-ssg--parse-buffer)))

(defun iduh-org-mode-ssg--parse-buffer ()
  "Parse the current buffer and return a structured document."
  (let ((title nil)
        (subtitle nil)
        (sections '())
        (current-section nil)
        (current-content '())
        (in-quote nil)
        (quote-content '())
        (line-number 0))
    
    (goto-char (point-min))
    
    (while (not (eobp))
      (let ((line (buffer-substring-no-properties
                   (line-beginning-position)
                   (line-end-position))))
        (setq line-number (1+ line-number))
        
        (cond
         ;; Check for sub-headings first (ERROR condition)
         ((string-match "^\\*\\*+[ \t]+" line)
          (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-subheading-error
                          "Sub-headings are not allowed (line %d): %s"
                          line-number line))
         
         ;; Title
         ((string-match "^#\\+TITLE:[ \t]*\\(.+\\)$" line)
          (setq title (match-string 1 line)))
         
         ;; Subtitle
         ((string-match "^#\\+SUBTITLE:[ \t]*\\(.+\\)$" line)
          (setq subtitle (match-string 1 line)))
         
         ;; Begin quote
         ((string-match "^#\\+BEGIN_QUOTE[ \t]*$" line)
          (setq in-quote t)
          (setq quote-content '()))
         
         ;; End quote
         ((string-match "^#\\+END_QUOTE[ \t]*$" line)
          (when in-quote
            (push (list :type 'quote :content (nreverse quote-content)) current-content)
            (setq in-quote nil)
            (setq quote-content '())))
         
         ;; Inside quote - collect lines
         (in-quote
          (push line quote-content))
         
         ;; Section heading (single *)
         ((string-match "^\\*[ \t]+\\(.+\\)$" line)
          ;; Save previous section if exists
          (when current-section
            (push (list :heading current-section
                        :content (nreverse current-content))
                  sections))
          ;; Start new section
          (setq current-section (match-string 1 line))
          (setq current-content '()))
         
         ;; Image link with mandatory alt text
         ((string-match "^[ \t]*\\[\\[\\([^]]+\\)\\]\\[\\([^]]+\\)\\]\\][ \t]*$" line)
          (let ((src (match-string 1 line))
                (alt (match-string 2 line)))
            (push (list :type 'image :src src :alt alt) current-content)))
         
         ;; Image link without alt text (ERROR)
         ((string-match "^[ \t]*\\[\\[\\([^]]+\\)\\]\\][ \t]*$" line)
          (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-image-error
                          "Image must have alt text (line %d): %s\nUse: [[image.png][Alt text description]]"
                          line-number line))
         
         ;; Skip other org directives
         ((string-match "^#\\+" line)
          nil)
         
         ;; Empty line
         ((string-match "^[ \t]*$" line)
          nil)
         
         ;; Regular paragraph text
         (t
          (let ((trimmed (string-trim line)))
            (when (> (length trimmed) 0)
              (push (list :type 'paragraph :text trimmed) current-content))))))
      
      (forward-line 1))
    
    ;; Save the last section
    (when current-section
      (push (list :heading current-section
                  :content (nreverse current-content))
            sections))
    
    ;; Check for unclosed quote
    (when in-quote
      (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-parse-error
                      "Unclosed quote block (missing #+END_QUOTE)"))
    
    (list :title title
          :subtitle subtitle
          :sections (nreverse sections))))

;;; ============================================================================
;;; Inline Formatting
;;; ============================================================================

(defun iduh-org-mode-ssg--format-inline (text)
  "Convert inline Org formatting in TEXT to HTML spans with CSS classes.
Supports *bold*, /italic/, _underline_, and +strikethrough+.
Uses placeholders to avoid regex conflicts when multiple formats are adjacent."
  (let ((result text))
    ;; Use placeholder tokens that contain NO formatting chars (*, /, _, +)
    ;; Process italic FIRST since its marker / appears in closing tags
    
    ;; Italic: /text/ - be careful not to match URLs or paths
    ;; Must process before others since "/" could appear in placeholders
    (setq result
          (replace-regexp-in-string
           "\\([^:]\\)/\\([^/\n]+?\\)/"
           "\\1~OSSI~\\2~OSSIe~"
           result))
    ;; Handle italic at start of string
    (when (string-match "^/\\([^/\n]+?\\)/" result)
      (setq result
            (replace-regexp-in-string
             "^/\\([^/\n]+?\\)/"
             "~OSSI~\\1~OSSIe~"
             result)))
    
    ;; Bold: *text*
    (setq result
          (replace-regexp-in-string
           "\\*\\([^*\n]+?\\)\\*"
           "~OSSB~\\1~OSSBe~"
           result))
    
    ;; Underline: _text_
    (setq result
          (replace-regexp-in-string
           "_\\([^_\n]+?\\)_"
           "~OSSU~\\1~OSSUe~"
           result))
    
    ;; Strikethrough: +text+
    (setq result
          (replace-regexp-in-string
           "\\+\\([^+\n]+?\\)\\+"
           "~OSSS~\\1~OSSSe~"
           result))
    
    ;; Now convert placeholders to actual HTML
    (setq result (replace-regexp-in-string "~OSSB~" "<span class=\"bold\">" result t t))
    (setq result (replace-regexp-in-string "~OSSBe~" "</span>" result t t))
    (setq result (replace-regexp-in-string "~OSSI~" "<span class=\"italic\">" result t t))
    (setq result (replace-regexp-in-string "~OSSIe~" "</span>" result t t))
    (setq result (replace-regexp-in-string "~OSSU~" "<span class=\"underline\">" result t t))
    (setq result (replace-regexp-in-string "~OSSUe~" "</span>" result t t))
    (setq result (replace-regexp-in-string "~OSSS~" "<span class=\"strikethrough\">" result t t))
    (setq result (replace-regexp-in-string "~OSSSe~" "</span>" result t t))
    
    result))

(defun iduh-org-mode-ssg--escape-html (text)
  "Escape HTML special characters in TEXT."
  (let ((result text))
    (setq result (replace-regexp-in-string "&" "&amp;" result))
    (setq result (replace-regexp-in-string "<" "&lt;" result))
    (setq result (replace-regexp-in-string ">" "&gt;" result))
    (setq result (replace-regexp-in-string "\"" "&quot;" result))
    result))

;;; ============================================================================
;;; HTML Generation
;;; ============================================================================

(defun iduh-org-mode-ssg--generate-html (doc css-path)
  "Generate HTML string from parsed document DOC, linking to CSS-PATH."
  (let ((title (or (plist-get doc :title) "Untitled"))
        (subtitle (plist-get doc :subtitle))
        (sections (plist-get doc :sections)))
    (concat
     ;; DOCTYPE and HTML opening
     "<!DOCTYPE html>\n"
     "<html lang=\"" iduh-org-mode-ssg-default-lang "\">\n"
     "<head>\n"
     "  <meta charset=\"UTF-8\">\n"
     "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
     "  <title>" (iduh-org-mode-ssg--escape-html title) "</title>\n"
     "  <meta name=\"generator\" content=\"iduh-org-mode-ssg\">\n"
     "  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
     "  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
     "  <link href=\"" iduh-org-mode-ssg-google-fonts-url "\" rel=\"stylesheet\">\n"
     "  <link rel=\"stylesheet\" href=\"" css-path "\">\n"
     "</head>\n"
     "<body>\n"
     "  <article>\n"
     ;; Header with title and subtitle
     "    <header>\n"
     "      <h1 class=\"title\">" (iduh-org-mode-ssg--format-inline (iduh-org-mode-ssg--escape-html title)) "</h1>\n"
     (if subtitle
         (concat "      <p class=\"subtitle\">"
                 (iduh-org-mode-ssg--format-inline (iduh-org-mode-ssg--escape-html subtitle))
                 "</p>\n")
       "")
     "    </header>\n"
     ;; Sections
     (mapconcat #'iduh-org-mode-ssg--generate-section sections "\n")
     "\n  </article>\n"
     "</body>\n"
     "</html>\n")))

(defun iduh-org-mode-ssg--generate-section (section)
  "Generate HTML for a SECTION."
  (let ((heading (plist-get section :heading))
        (content (plist-get section :content)))
    (concat
     "    <section>\n"
     "      <h2>" (iduh-org-mode-ssg--format-inline (iduh-org-mode-ssg--escape-html heading)) "</h2>\n"
     (mapconcat #'iduh-org-mode-ssg--generate-content content "")
     "    </section>")))

(defun iduh-org-mode-ssg--generate-content (item)
  "Generate HTML for a content ITEM (paragraph, image, or quote)."
  (let ((type (plist-get item :type)))
    (pcase type
      ('paragraph
       (concat "      <p>"
               (iduh-org-mode-ssg--format-inline (iduh-org-mode-ssg--escape-html (plist-get item :text)))
               "</p>\n"))
      ('image
       (let ((src (plist-get item :src))
             (alt (plist-get item :alt)))
         (concat "      <figure>\n"
                 "        <img src=\"" (iduh-org-mode-ssg--escape-html src) "\" "
                 "alt=\"" (iduh-org-mode-ssg--escape-html alt) "\">\n"
                 "        <figcaption>" (iduh-org-mode-ssg--escape-html alt) "</figcaption>\n"
                 "      </figure>\n")))
      ('quote
       (let ((lines (plist-get item :content)))
         (concat "      <blockquote>\n"
                 (mapconcat
                  (lambda (line)
                    (let ((trimmed (string-trim line)))
                      (if (> (length trimmed) 0)
                          (concat "        <p>"
                                  (iduh-org-mode-ssg--format-inline (iduh-org-mode-ssg--escape-html trimmed))
                                  "</p>\n")
                        "")))
                  lines "")
                 "      </blockquote>\n")))
      (_ ""))))

;;; ============================================================================
;;; Public API
;;; ============================================================================

;;;###autoload
(defun iduh-org-mode-ssg-generate (input-file output-file css-path)
  "Generate HTML from INPUT-FILE and write to OUTPUT-FILE.
CSS-PATH is the path to the stylesheet (relative to the output HTML)."
  (interactive
   (list
    (read-file-name "Input Org file: " nil nil t nil
                    (lambda (f) (or (file-directory-p f)
                                     (string-suffix-p ".org" f))))
    (read-file-name "Output HTML file: " nil nil nil "output.html")
    (read-string "CSS path (relative to HTML): " "style.css")))
  
  (unless (file-exists-p input-file)
    (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-error "Input file does not exist: %s" input-file))
  
  (let* ((doc (iduh-org-mode-ssg--parse-file input-file))
         (html (iduh-org-mode-ssg--generate-html doc css-path)))
    (with-temp-file output-file
      (insert html))
    (message "Generated: %s" output-file)
    output-file))

;;;###autoload
(defun iduh-org-mode-ssg-generate-interactive ()
  "Interactively generate HTML from an Org file."
  (interactive)
  (call-interactively #'iduh-org-mode-ssg-generate))

;;;###autoload
(defun iduh-org-mode-ssg-preview (input-file)
  "Generate and preview HTML from INPUT-FILE in browser."
  (interactive
   (list (read-file-name "Input Org file: " nil nil t nil
                         (lambda (f) (or (file-directory-p f)
                                          (string-suffix-p ".org" f))))))
  (let* ((temp-html (make-temp-file "iduh-org-mode-ssg-preview-" nil ".html"))
         (temp-css (expand-file-name "style.css" (file-name-directory temp-html)))
         (css-source (expand-file-name "style.css"
                                        (file-name-directory
                                         (or load-file-name buffer-file-name)))))
    ;; Copy CSS to temp location
    (when (file-exists-p css-source)
      (copy-file css-source temp-css t))
    ;; Generate HTML
    (iduh-org-mode-ssg-generate input-file temp-html "style.css")
    ;; Open in browser
    (browse-url-of-file temp-html)))

(provide 'iduh-org-mode-ssg)

;;; iduh-org-mode-ssg.el ends here
