;;; iduh-org-mode-ssg-skeleton.el --- Skeleton verification for iduh-org-mode-ssg -*- lexical-binding: t; -*-

;; Author: rmnull(Generated by AI Assistant)
;; Version: 1.1.1
;; Package-Requires: ((emacs "27.1"))

;;; Commentary:

;; Verifies that a skeleton directory has the expected layout for
;; `iduh-org-ssg-build-site' and `iduh-org-ssg-generate-file'.
;;
;; Expected layout:
;;   <skeleton>/
;;     templates/
;;       base.html
;;       header.html
;;       footer.html
;;     static/
;;       css/style.css
;;       asset/site-logo.svg

;;; Code:

(require 'cl-lib)

(define-error 'iduh-org-mode-ssg-skeleton-error
  "IDUH-Org-Mode-SSG Skeleton Error")

(defun iduh-org-ssg-verify-skeleton (skeleton-dir &optional no-error)
  "Verify SKELETON-DIR has the expected layout.

If NO-ERROR is non-nil, return a plist:
  (:ok BOOL :errors (STRING...) :skeleton-root DIR)
instead of signaling an error.

Otherwise, signal `iduh-org-mode-ssg-skeleton-error' on failure and return t
on success."
  (interactive (list (read-directory-name "Skeleton directory: " default-directory nil t)))
  (let* ((root (file-name-as-directory (expand-file-name skeleton-dir)))
         (templates (expand-file-name "templates/" root))
         (static (expand-file-name "static/" root))
         (required-files
          (list (expand-file-name "templates/base.html" root)
                (expand-file-name "templates/header.html" root)
                (expand-file-name "templates/footer.html" root)
                (expand-file-name "static/css/style.css" root)
                (expand-file-name "static/asset/site-logo.svg" root)))
         (errors '()))
    (unless (file-directory-p root)
      (push (format "Skeleton directory does not exist: %s" root) errors))
    (unless (file-directory-p templates)
      (push (format "Missing templates directory: %s" templates) errors))
    (unless (file-directory-p static)
      (push (format "Missing static directory: %s" static) errors))
    (dolist (f required-files)
      (unless (file-readable-p f)
        (push (format "Missing required file: %s" f) errors)))
    (setq errors (nreverse errors))
    (cond
     (errors
      (if no-error
          (list :ok nil :errors errors :skeleton-root root)
        (signal 'iduh-org-mode-ssg-skeleton-error
                (list (mapconcat #'identity errors "\n")))))
     (t
      (when (called-interactively-p 'interactive)
        (message "Skeleton OK: %s" root))
      (if no-error
          (list :ok t :errors nil :skeleton-root root)
        t)))))

(provide 'iduh-org-mode-ssg-skeleton)

;;; iduh-org-mode-ssg-skeleton.el ends here
