;;; iduh-org-mode-ssg.el --- Minimal Static Site Generator for Org-Mode -*- lexical-binding: t; -*-

;; Author: rmnull(Generated by AI Assistant)
;; Version: 1.0.2
;; Keywords: org, html, static-site-generator
;; Package-Requires: ((emacs "27.1"))

;;; Commentary:

;; A minimal static site generator that converts a stripped-down Org-Mode
;; document into a clean, styled HTML file.
;;
;; Supported Org-Mode features:
;; - #+TITLE: Document title
;; - #+SUBTITLE: Document subtitle
;; - * Heading (single level only, creates sections)
;; - Paragraph text
;; - [[image.png][alt text]] Image embedding (alt text mandatory)
;; - #+BEGIN_QUOTE ... #+END_QUOTE Text quoting
;; - *bold* /italic/ _underline_ +strikethrough+ inline formatting
;;
;; NOT supported (throws error):
;; - ** Sub-headings (or any deeper nesting)
;;
;; Usage:
;;   (iduh-org-mode-ssg-generate "input.org" "output.html" "style.css")
;;
;; Or interactively:
;;   M-x iduh-org-mode-ssg-generate-interactive

;;; Code:

(require 'cl-lib)
(require 'org-element)
(require 'ox)
;; Optional: skeleton verification helpers (new file).
(require 'iduh-org-mode-ssg-skeleton nil t)

;;; ============================================================================
;;; Configuration
;;; ============================================================================

(defgroup iduh-org-mode-ssg nil
  "Minimal static site generator for Org-Mode."
  :group 'org
  :prefix "iduh-org-mode-ssg-")

(defcustom iduh-org-mode-ssg-default-lang "en"
  "Default language attribute for generated HTML."
  :type 'string
  :group 'iduh-org-mode-ssg)

(defcustom iduh-org-mode-ssg-google-fonts-url
  "https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=JetBrains+Mono:wght@400;500&family=Merriweather:ital,wght@0,400;1,400&family=Playfair+Display:wght@600;700&display=swap"
  "Google Fonts URL to include in generated HTML."
  :type 'string
  :group 'iduh-org-mode-ssg)

(defcustom iduh-org-ssg-skeleton-directory "skeleton/"
  "Directory containing the site \"skeleton\" (templates + static assets).

Expected layout:
- templates/ (e.g. base.html, header.html, footer.html)
- static/    (assets copied verbatim to the output directory)
The generator derives templates/static/CSS/logo paths from this directory."
  :type 'string
  :group 'iduh-org-mode-ssg)

(defcustom iduh-org-ssg-output-directory "public/"
  "Output directory for generated HTML files."
  :type 'string
  :group 'iduh-org-mode-ssg)

(defcustom iduh-org-ssg-posts-directory "posts/"
  "Directory (relative to project root or absolute) containing Org posts."
  :type 'string
  :group 'iduh-org-mode-ssg)

(defconst iduh-org-ssg--default-css-path "css/style.css"
  "Default CSS path relative to the output directory.")

(defconst iduh-org-ssg--default-logo-path "asset/site-logo.svg"
  "Default logo path relative to the output directory.")

;;; ============================================================================
;;; Error Handling
;;; ============================================================================

(define-error 'iduh-org-mode-ssg-error "IDUH-Org-Mode-SSG Error")
(define-error 'iduh-org-mode-ssg-subheading-error "Sub-heading not allowed" 'iduh-org-mode-ssg-error)
(define-error 'iduh-org-mode-ssg-image-error "Image syntax error" 'iduh-org-mode-ssg-error)
(define-error 'iduh-org-mode-ssg-parse-error "Parse error" 'iduh-org-mode-ssg-error)

(defvar iduh-org-ssg--current-input-file nil
  "Path to the Org file currently being processed.")

(defvar iduh-org-ssg--current-output-dir nil
  "Path to the output directory for the current build.")

(defvar iduh-org-ssg--current-post-slug nil
  "Slug of the post currently being processed.")

;; Internal, derived paths for a given run (set by build/generate entrypoints).
(defvar iduh-org-ssg--templates-dir nil
  "Absolute path to the templates directory for the current run.")

(defvar iduh-org-ssg--static-dir nil
  "Absolute path to the static directory for the current run.")

(defun iduh-org-ssg--resolve-layout (project-root &optional skeleton)
  "Resolve skeleton-derived layout given PROJECT-ROOT and optional SKELETON.

SKELETON may be absolute or relative to PROJECT-ROOT.
Returns a plist with :skeleton-root, :templates-dir, :static-dir."
  (let* ((skeleton-root (expand-file-name (or skeleton iduh-org-ssg-skeleton-directory) project-root))
         (templates-dir (expand-file-name "templates/" skeleton-root))
         (static-dir (expand-file-name "static/" skeleton-root)))
    (list :skeleton-root skeleton-root
          :templates-dir templates-dir
          :static-dir static-dir)))

;;; ============================================================================
;;; Path resolution helpers
;;; ============================================================================

(defun iduh-org-ssg--resolve-skeleton-root (project-root &optional skeleton)
  "Resolve skeleton root directory given PROJECT-ROOT and optional SKELETON.

Returns an absolute directory name, or nil when no skeleton is configured."
  (let ((skel (or skeleton iduh-org-ssg-skeleton-directory)))
    (when (and skel (stringp skel) (not (string-empty-p skel)))
      (expand-file-name skel project-root))))

(defun iduh-org-ssg--resolve-skeleton-subdir (project-root subdir &optional skeleton)
  "Resolve SUBDIR within the skeleton for PROJECT-ROOT.

SUBDIR should be a relative path like \"templates/\" or \"static/\".
Returns an absolute directory path or nil if skeleton is not configured."
  (let ((root (iduh-org-ssg--resolve-skeleton-root project-root skeleton)))
    (when root
      (expand-file-name subdir root))))

(defvar iduh-org-ssg--image-extensions
  '("jpg" "jpeg" "png" "gif" "svg" "webp" "bmp" "tiff")
  "List of file extensions considered to be images.")

(defun iduh-org-ssg--image-p (path)
  "Return t if PATH points to an image file based on its extension."
  (let ((ext (downcase (file-name-extension path))))
    (member ext iduh-org-ssg--image-extensions)))

(defun iduh-org-ssg--slugify (title)
  "Convert TITLE to a URL-friendly slug for use as filename.
E.g., 'My First Post' becomes 'my-first-post'."
  (let ((slug (downcase title)))
    ;; Replace spaces and underscores with hyphens
    (setq slug (replace-regexp-in-string "[ _]+" "-" slug))
    ;; Remove non-alphanumeric characters except hyphens
    (setq slug (replace-regexp-in-string "[^a-z0-9-]" "" slug))
    ;; Remove multiple consecutive hyphens
    (setq slug (replace-regexp-in-string "-+" "-" slug))
    ;; Remove leading/trailing hyphens
    (setq slug (replace-regexp-in-string "^-\\|-$" "" slug))
    slug))

(defun iduh-org-ssg--handle-file-link (path)
  "Handle a file: link PATH.
If it's an Org file in the same directory, link to its generated HTML.
If it's an Org file elsewhere or any other file, copy it to post-assets."
  (if (or (not iduh-org-ssg--current-post-slug)
          (not iduh-org-ssg--current-input-file))
      path
    (let* ((input-dir (file-name-as-directory (file-name-directory (expand-file-name iduh-org-ssg--current-input-file))))
           (src-file (expand-file-name path input-dir))
           (is-org (string-suffix-p ".org" path))
           (in-same-dir (string= (file-name-directory (expand-file-name src-file)) input-dir)))
      (if (and is-org in-same-dir)
          (if (file-exists-p src-file)
              (let* ((linked-doc (iduh-org-mode-ssg--parse-file src-file))
                     (linked-title (plist-get linked-doc :title)))
                (concat (iduh-org-ssg--slugify (or linked-title (file-name-base src-file))) ".html"))
            path)
        ;; Copy to assets/post_resources/<post_id>/
        (let* ((filename (file-name-nondirectory src-file))
               (assets-rel-dir (concat "assets/post_resources/" iduh-org-ssg--current-post-slug "/"))
               (dest-dir (expand-file-name assets-rel-dir (or iduh-org-ssg--current-output-dir iduh-org-ssg-output-directory)))
               (dest-file (expand-file-name filename dest-dir))
               (web-link (concat assets-rel-dir filename)))
          (if (file-exists-p src-file)
              (progn
                (unless (file-directory-p dest-dir)
                  (make-directory dest-dir t))
                (copy-file src-file dest-file t)
                web-link)
            path))))))

(defun iduh-org-mode-ssg--error (type message &rest args)
  "Signal an iduh-org-mode-ssg error of TYPE with MESSAGE formatted with ARGS."
  (signal type (list (apply #'format message args))))

;;; ============================================================================
;;; AST Parsing Functions
;;; ============================================================================

(defun iduh-org-mode-ssg--parse-file (filepath)
  "Parse an Org file at FILEPATH using org-element AST.
Returns a plist with :title, :subtitle, :date, :author, :description, and :sections."
  (with-temp-buffer
    (insert-file-contents filepath)
    (org-mode)
    (iduh-org-mode-ssg--parse-buffer)))

(defun iduh-org-mode-ssg--get-keyword (ast keyword)
  "Extract KEYWORD value from AST."
  (org-element-map ast 'keyword
    (lambda (kw)
      (when (string= (upcase (org-element-property :key kw)) (upcase keyword))
        (org-element-property :value kw)))
    nil t))

(defun iduh-org-mode-ssg--parse-buffer ()
  "Parse the current buffer using org-element AST and return a structured document."
  (let* ((ast (org-element-parse-buffer))
         (title (iduh-org-mode-ssg--get-keyword ast "TITLE"))
         (iduh-org-ssg--current-post-slug (if title
                                             (iduh-org-ssg--slugify title)
                                           (if iduh-org-ssg--current-input-file
                                               (file-name-base iduh-org-ssg--current-input-file)
                                             "untitled")))
         (subtitle (iduh-org-mode-ssg--get-keyword ast "SUBTITLE"))
         (date (iduh-org-mode-ssg--get-keyword ast "DATE"))
         (author (iduh-org-mode-ssg--get-keyword ast "AUTHOR"))
         (description (iduh-org-mode-ssg--get-keyword ast "DESCRIPTION"))
         ;; Extract only level 1 headlines
         (sections (org-element-map ast 'headline
                     (lambda (headline)
                       (when (= (org-element-property :level headline) 1)
                         (list :heading (org-element-property :title headline)
                               :content (iduh-org-mode-ssg--parse-section-content headline)))))))
    
    (setq sections (delq nil sections))
    
    (org-element-map ast 'headline
      (lambda (headline)
        (when (> (org-element-property :level headline) 1)
          (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-subheading-error
                                    "Sub-headings are not allowed: %s"
                                    (org-element-property :raw-value headline)))))

    (list :title title
          :subtitle subtitle
          :date date
          :author author
          :description description
          :sections sections)))

(defun iduh-org-mode-ssg--parse-section-content (headline)
  "Parse the content of a HEADLINE element and return a list of content items."
  (let* ((section (org-element-map headline 'section #'identity nil t))
         (elements (and section (org-element-contents section)))
         (items '()))
    (dolist (element elements)
      (let ((type (org-element-type element)))
        (cond
         ;; Paragraph (Check for standalone image)
         ((eq type 'paragraph)
          (let* ((contents (org-element-contents element))
                 (non-blank-contents (cl-remove-if (lambda (c) (and (stringp c) (string-blank-p c))) contents))
                 (first-child (car non-blank-contents)))
            (if (and (= (length non-blank-contents) 1)
                     (eq (org-element-type first-child) 'link)
                     (string= (org-element-property :type first-child) "file")
                     (iduh-org-ssg--image-p (org-element-property :path first-child)))
                (let* ((src (iduh-org-ssg--handle-file-link (org-element-property :path first-child)))
                       (desc (org-element-contents first-child))
                       ;; Extract plain text from description for alt/caption
                       (alt (if desc
                                (string-trim (org-element-interpret-data desc))
                              "")))
                  (if (> (length alt) 0)
                      (push (list :type 'image :src src :alt alt) items)
                    (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-image-error
                                              "Image must have alt text: [[%s]]" src)))
              (push (list :type 'paragraph :content contents) items))))
         
         ;; Quote block
         ((eq type 'quote-block)
          (let ((quote-lines '()))
            (dolist (child (org-element-contents element))
              (when (eq (org-element-type child) 'paragraph)
                (push (org-element-contents child) quote-lines)))
            (push (list :type 'quote :content (nreverse quote-lines)) items)))

         ;; List
         ((eq type 'plain-list)
          (let ((list-items '()))
            (dolist (child (org-element-contents element))
              (when (eq (org-element-type child) 'item)
                (push (org-element-contents (car (org-element-contents child)))
                      list-items)))
            (push (list :type 'list :content (nreverse list-items)) items))))))
    (nreverse items)))

;;; ============================================================================
;;; Inline Formatting
;;; ============================================================================

;;; ============================================================================
;;; AST Rendering (No Regex Magic)
;;; ============================================================================

(defun iduh-org-mode-ssg--render-ast (data)
  "Convert AST DATA (element, object, or list) to HTML string without regex."
  (cond
   ((null data) "")
   ((stringp data) (iduh-org-mode-ssg--escape-html data))
   ((listp (car-safe data)) (mapconcat #'iduh-org-mode-ssg--render-ast data ""))
   ((and (listp data) (not (symbolp (car data)))) (mapconcat #'iduh-org-mode-ssg--render-ast data ""))
   (t
    (let* ((type (org-element-type data))
           (contents (org-element-contents data))
           (post-blank (or (org-element-property :post-blank data) 0))
           (blank-str (make-string post-blank ?\s))
           (html-content
            (pcase type
              ('bold (concat "<span class=\"bold\">" (iduh-org-mode-ssg--render-ast contents) "</span>"))
              ('italic (concat "<span class=\"italic\">" (iduh-org-mode-ssg--render-ast contents) "</span>"))
              ('underline (concat "<span class=\"underline\">" (iduh-org-mode-ssg--render-ast contents) "</span>"))
              ('strike-through (concat "<span class=\"strikethrough\">" (iduh-org-mode-ssg--render-ast contents) "</span>"))
              ('code (concat "<code>" (iduh-org-mode-ssg--escape-html (org-element-property :value data)) "</code>"))
              ('verbatim (concat "<code>" (iduh-org-mode-ssg--escape-html (org-element-property :value data)) "</code>"))
              ('link 
               (let ((link-type (org-element-property :type data))
                     (path (org-element-property :path data)))
                 (if (string= link-type "file")
                     (let* ((is-org (string-suffix-p ".org" path))
                            (is-image (iduh-org-ssg--image-p path))
                            (input-dir (and iduh-org-ssg--current-input-file 
                                            (file-name-as-directory (file-name-directory (expand-file-name iduh-org-ssg--current-input-file)))))
                            (src-file (and input-dir (expand-file-name path input-dir)))
                            (in-same-dir (and src-file input-dir (string= (file-name-directory (expand-file-name src-file)) input-dir)))
                            (final-path (iduh-org-ssg--handle-file-link path))
                            (rendered-contents (if (and contents (> (length contents) 0))
                                                  (iduh-org-mode-ssg--render-ast contents)
                                                "")))
                       (cond
                        (is-image
                         (let* ((desc (org-element-contents data))
                                (alt (if (> (length desc) 0)
                                         (string-trim (iduh-org-mode-ssg--render-ast desc))
                                       (iduh-org-mode-ssg--escape-html (file-name-nondirectory path)))))
                           (iduh-org-mode-ssg--render-image final-path alt)))
                        (t
                         (let ((label (if (> (length rendered-contents) 0)
                                          rendered-contents
                                        (if (and is-org in-same-dir (file-exists-p src-file))
                                            (let* ((linked-doc (iduh-org-mode-ssg--parse-file src-file))
                                                   (linked-title (plist-get linked-doc :title)))
                                              (iduh-org-mode-ssg--escape-html (or linked-title (file-name-base src-file))))
                                          (iduh-org-mode-ssg--escape-html path)))))
                           (concat "<a href=\"" (iduh-org-mode-ssg--escape-html final-path) "\">" label "</a>")))))
                   (concat "<a href=\"" (org-element-property :raw-link data) "\">" 
                           (if (and contents (> (length contents) 0))
                               (iduh-org-mode-ssg--render-ast contents)
                             (org-element-property :raw-link data))
                           "</a>"))))
              (_ (iduh-org-mode-ssg--render-ast contents)))))
      (concat html-content blank-str)))))

(defun iduh-org-mode-ssg--escape-html (text)
  "Escape HTML special characters in TEXT."
  (if (not (stringp text))
      ""
    (let ((result text))
      (setq result (replace-regexp-in-string "&" "&amp;" result))
      (setq result (replace-regexp-in-string "<" "&lt;" result))
      (setq result (replace-regexp-in-string ">" "&gt;" result))
      (setq result (replace-regexp-in-string "\"" "&quot;" result))
      result)))

;;; ============================================================================
;;; Date Formatting
;;; ============================================================================

(defconst iduh-org-mode-ssg--month-names
  '("Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec")
  "Short month names for date formatting.")

(defun iduh-org-mode-ssg--format-date (date-string)
  "Format DATE-STRING as 'Published on DD Mon YYYY'.
DATE-STRING should be in YYYY-MM-DD format."
  (when date-string
    (if (string-match "^\\([0-9]\\{4\\}\\)-\\([0-9]\\{2\\}\\)-\\([0-9]\\{2\\}\\)$" date-string)
        (let* ((year (match-string 1 date-string))
               (month (string-to-number (match-string 2 date-string)))
               (day (string-to-number (match-string 3 date-string)))
               (month-name (nth (1- month) iduh-org-mode-ssg--month-names)))
          (format "Published on %d %s %s" day month-name year))
      ;; If not in expected format, return as-is with prefix
      (concat "Published on " date-string))))

;;; ============================================================================
;;; Template Processing
;;; ============================================================================

(defun iduh-org-mode-ssg--load-template (template-path)
  "Load template from TEMPLATE-PATH if it exists, otherwise return nil."
  (when (and template-path (file-exists-p template-path))
    (with-temp-buffer
      (insert-file-contents template-path)
      (buffer-string))))

(defun iduh-org-mode-ssg--process-template (template replacements)
  "Process TEMPLATE string, replacing placeholders with values from REPLACEMENTS plist.
Placeholders should be in the format {{key}}."
  (when template
    (let ((result template))
      (cl-loop for (key value) on replacements by #'cddr
               do (let ((placeholder (format "{{%s}}" (substring (symbol-name key) 1))))
                    (setq result (replace-regexp-in-string placeholder (or (format "%s" (or value "")) "") result t t))))
      result)))

;;; ============================================================================
;;; HTML Generation
;;; ============================================================================

(defun iduh-org-mode-ssg--generate-html (doc css-path &optional header-template footer-template)
  "Generate HTML string from parsed document DOC, linking to CSS-PATH.
Optional HEADER-TEMPLATE and FOOTER-TEMPLATE are pre-loaded template strings."
  (let* ((title (or (plist-get doc :title) "Untitled"))
         (subtitle (plist-get doc :subtitle))
         (date (plist-get doc :date))
         (description (plist-get doc :description))
         (sections (plist-get doc :sections))
         (author (or (plist-get doc :author) ""))
         ;; Base replacements for templates
         (replacements (list :title (string-trim (iduh-org-mode-ssg--render-ast title))
                             :date (iduh-org-mode-ssg--escape-html date)
                             :author author
                             :logo_path iduh-org-ssg--default-logo-path
                             :year (format-time-string "%Y")))
         (processed-header (iduh-org-mode-ssg--process-template header-template replacements))
         (processed-footer (iduh-org-mode-ssg--process-template footer-template replacements))
         (base-template-str (or (and iduh-org-ssg--templates-dir
                                     (iduh-org-mode-ssg--load-template
                                      (expand-file-name "base.html" iduh-org-ssg--templates-dir)))
                                iduh--default-base-template))
         
         (meta (concat (when date
                         (concat "  <meta name=\"date\" content=\"" (iduh-org-mode-ssg--escape-html date) "\">\n"))
                       (when description
                         (concat "  <meta name=\"description\" content=\"" (iduh-org-mode-ssg--escape-html description) "\">\n"))))
         
         (formatted-subtitle (if subtitle
                                 (concat "<p class=\"subtitle\">"
                                         (string-trim (iduh-org-mode-ssg--render-ast subtitle))
                                         "</p>")
                                ""))
         (formatted-date (if date
                             (concat "<time class=\"published-date\" datetime=\"" (iduh-org-mode-ssg--escape-html date) "\">"
                                     (iduh-org-mode-ssg--format-date date)
                                     "</time>")
                           ""))
         (content (mapconcat #'iduh-org-mode-ssg--generate-section sections "\n"))
         
         (all-replacements (append replacements
                                   (list :lang iduh-org-mode-ssg-default-lang
                                         :meta (string-trim meta)
                                         :google_fonts_url iduh-org-mode-ssg-google-fonts-url
                                         :css_path css-path
                                         :header (or (and processed-header (string-trim processed-header)) "")
                                         :formatted_title (string-trim (iduh-org-mode-ssg--render-ast title))
                                         :formatted_subtitle formatted-subtitle
                                         :formatted_date formatted-date
                                         :content (string-trim content)
                                         :footer (or (and processed-footer (string-trim processed-footer)) "")))))
    (iduh-org-mode-ssg--process-template base-template-str all-replacements)))

(defconst iduh--default-base-template
  "<!DOCTYPE html>
<html lang=\"{{lang}}\">
<head>
  <meta charset=\"UTF-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
  <title>{{title}}</title>
  <meta name=\"generator\" content=\"iduh-org-mode-ssg\">
  {{meta}}
  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">
  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>
  <link href=\"{{google_fonts_url}}\" rel=\"stylesheet\">
  <link rel=\"stylesheet\" href=\"{{css_path}}\">
</head>
<body>
  {{header}}
  <article>
    <header>
      <h1 class=\"title\">{{formatted_title}}</h1>
      {{formatted_subtitle}}
      {{formatted_date}}
    </header>
    {{content}}
  </article>
  {{footer}}
</body>
</html>"
  "Default base HTML template.")


(defun iduh-org-mode-ssg--generate-section (section)
  "Generate HTML for a SECTION."
  (let ((heading (plist-get section :heading))
        (content (plist-get section :content)))
    (concat
     "    <section>\n"
     "      <h2>" (string-trim (iduh-org-mode-ssg--render-ast heading)) "</h2>\n"
     (mapconcat #'iduh-org-mode-ssg--generate-content content "")
     "    </section>")))

(defun iduh-org-mode-ssg--render-image (src alt)
  "Render an image with SRC and ALT text wrapped in a <figure> tag."
  (concat "      <figure>\n"
          "        <img src=\"" (iduh-org-mode-ssg--escape-html src) "\" "
          "alt=\"" (iduh-org-mode-ssg--escape-html alt) "\">\n"
          "        <figcaption>" (iduh-org-mode-ssg--escape-html alt) "</figcaption>\n"
          "      </figure>\n"))

(defun iduh-org-mode-ssg--generate-content (item)
  "Generate HTML for a content ITEM (paragraph, image, or quote)."
  (let ((type (plist-get item :type)))
    (pcase type
      ('paragraph
       (concat "      <p>" (string-trim (iduh-org-mode-ssg--render-ast (plist-get item :content))) "</p>\n"))
      ('image
       (iduh-org-mode-ssg--render-image (plist-get item :src) (plist-get item :alt)))
      ('quote
       (let ((contents (plist-get item :content)))
         (concat "      <blockquote>\n"
                 (mapconcat
                  (lambda (content)
                    (let ((rendered (string-trim (iduh-org-mode-ssg--render-ast content))))
                      (if (> (length rendered) 0)
                          (concat "        <p>" rendered "</p>\n")
                        "")))
                  contents "")
                 "      </blockquote>\n")))
      ('list
       (let ((items (plist-get item :content)))
         (concat "      <ul>\n"
                 (mapconcat
                  (lambda (li)
                    (concat "        <li>" (string-trim (iduh-org-mode-ssg--render-ast li)) "</li>\n"))
                  items "")
                 "      </ul>\n")))
      (_ ""))))


;;; ============================================================================
;;; Public API
;;; ============================================================================


(defun iduh-org-ssg--copy-directory-contents (src-dir dest-dir)
  "Recursively copy contents of SRC-DIR to DEST-DIR."
  (when (file-directory-p src-dir)
    (unless (file-directory-p dest-dir)
      (make-directory dest-dir t))
    (dolist (file (directory-files src-dir t))
      (let ((filename (file-name-nondirectory file))
            (dest-file (expand-file-name (file-name-nondirectory file) dest-dir)))
        (unless (member filename '("." ".."))
          (if (file-directory-p file)
              (iduh-org-ssg--copy-directory-contents 
               file 
               (expand-file-name filename dest-dir))
            (copy-file file dest-file t)))))))

;;;###autoload
(defun iduh-org-mode-ssg-generate (input-file output-file css-path)
  "Generate HTML from INPUT-FILE and write to OUTPUT-FILE.
CSS-PATH is the path to the stylesheet (relative to the output HTML)."
  (interactive
   (list
    (read-file-name "Input Org file: " nil nil t nil
                    (lambda (f) (or (file-directory-p f)
                                     (string-suffix-p ".org" f))))
    (read-file-name "Output HTML file: " nil nil nil "output.html")
    (read-string "CSS path (relative to HTML): " "style.css")))
  
  (unless (file-exists-p input-file)
    (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-error "Input file does not exist: %s" input-file))
  
  (let* ((layout (iduh-org-ssg--resolve-layout default-directory))
         (iduh-org-ssg--templates-dir (plist-get layout :templates-dir))
         (iduh-org-ssg--current-input-file input-file)
         (iduh-org-ssg--current-output-dir (file-name-directory output-file))
         (doc (iduh-org-mode-ssg--parse-file input-file))
         (iduh-org-ssg--current-post-slug (iduh-org-ssg--slugify (or (plist-get doc :title) 
                                                                    (file-name-base input-file))))
         (_ (when (fboundp 'iduh-org-ssg-verify-skeleton)
              (iduh-org-ssg-verify-skeleton (plist-get layout :skeleton-root))))
     (header-template (and iduh-org-ssg--templates-dir
                           (iduh-org-mode-ssg--load-template
                            (expand-file-name "header.html" iduh-org-ssg--templates-dir))))
     (footer-template (and iduh-org-ssg--templates-dir
                           (iduh-org-mode-ssg--load-template
                            (expand-file-name "footer.html" iduh-org-ssg--templates-dir))))
     (html (iduh-org-mode-ssg--generate-html doc css-path header-template footer-template)))
    ;; Validate required fields
    (unless (plist-get doc :date)
      (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-parse-error
                      "Missing #+DATE field in %s. This field is mandatory." input-file))
    (with-temp-file output-file
      (insert html))
    (message "Generated: %s" output-file)
    output-file))

;;;###autoload
;;;###autoload
(cl-defun iduh-org-ssg-generate-file (input-file &optional output-dir &key skeleton lang fonts-url)
  "Generate HTML from INPUT-FILE into OUTPUT-DIR.
If OUTPUT-DIR is nil, uses `iduh-org-ssg-output-directory'.
The output filename is derived from the org file's #+TITLE.
Returns the path to the generated HTML file."
  (interactive
   (list
    (let ((posts-root (expand-file-name iduh-org-ssg-posts-directory default-directory)))
      (read-file-name "Input Org file: "
                      (if (file-directory-p posts-root) posts-root default-directory)
                      nil t nil
                      (lambda (f) (or (file-directory-p f)
                                      (string-suffix-p ".org" f)))))
    (read-directory-name "Output directory (leave empty for default): " 
                         iduh-org-ssg-output-directory nil t)))
  
  (unless (file-exists-p input-file)
    (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-error "Input file does not exist: %s" input-file))

  (let* ((output-dir (or (and output-dir (not (string-empty-p output-dir)) output-dir)
                        iduh-org-ssg-output-directory))
         (_ (unless (file-directory-p output-dir) (make-directory output-dir t)))
         (iduh-org-mode-ssg-default-lang (or lang iduh-org-mode-ssg-default-lang))
         (iduh-org-mode-ssg-google-fonts-url (or fonts-url iduh-org-mode-ssg-google-fonts-url))
         (project-root default-directory)
         (layout (iduh-org-ssg--resolve-layout project-root skeleton))
         (iduh-org-ssg--templates-dir (plist-get layout :templates-dir))
         (_ (when (fboundp 'iduh-org-ssg-verify-skeleton)
              (iduh-org-ssg-verify-skeleton (plist-get layout :skeleton-root))))
         (iduh-org-ssg--current-input-file input-file)
         (iduh-org-ssg--current-output-dir output-dir)
         (doc (iduh-org-mode-ssg--parse-file input-file))
         (iduh-org-ssg--current-post-slug (iduh-org-ssg--slugify (or (plist-get doc :title) 
                                                                    (file-name-base input-file))))
         (title (plist-get doc :title))
         (date (plist-get doc :date))
         (output-filename (if title
                              (concat iduh-org-ssg--current-post-slug ".html")
                            (concat (file-name-base input-file) ".html")))
         (output-file (expand-file-name output-filename output-dir))
         (header-template (and iduh-org-ssg--templates-dir
                               (iduh-org-mode-ssg--load-template
                                (expand-file-name "header.html" iduh-org-ssg--templates-dir))))
         (footer-template (and iduh-org-ssg--templates-dir
                               (iduh-org-mode-ssg--load-template
                                (expand-file-name "footer.html" iduh-org-ssg--templates-dir))))
         (html (iduh-org-mode-ssg--generate-html doc iduh-org-ssg--default-css-path header-template footer-template)))
    
    ;; Validate required fields
    (unless date
      (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-parse-error
                      "Missing #+DATE field in %s. This field is mandatory." input-file))
    
    (with-temp-file output-file
      (insert html))
    (message "Generated: %s" output-file)
    output-file))

;;;###autoload
;;;###autoload
(cl-defun iduh-org-ssg-build-site (&rest args)
  "Build the entire static site.
Supports keyword arguments to override global configuration:
:posts        - Source directory for org files
:output       - Output directory for generated HTML
:skeleton     - Skeleton directory (templates + static assets)
:base         - Project base directory (defaults to current directory)
:lang         - HTML language attribute
:fonts-url    - Google Fonts URL

If the first argument is not a keyword, it is treated as the :base directory.

This function:
1. Finds all .org files in posts directory
2. Generates HTML for each (with mandatory #+DATE validation)
3. Copies static assets to output directory
4. Returns the list of generated files."
  (interactive)
  
  (let* ((all-args (if (and args (not (keywordp (car args))))
                       (cons :base args)
                     args))
         (posts (plist-get all-args :posts))
         (output (plist-get all-args :output))
         (skeleton (plist-get all-args :skeleton))
         (base (plist-get all-args :base))
         (lang (plist-get all-args :lang))
         (fonts-url (plist-get all-args :fonts-url))

         ;; 1. Determine Project Root
         ;; Use :base if provided, otherwise default-directory.
         (project-root (expand-file-name (or base default-directory)))
         
         (iduh-org-mode-ssg-default-lang (or lang iduh-org-mode-ssg-default-lang))
         (iduh-org-mode-ssg-google-fonts-url (or fonts-url iduh-org-mode-ssg-google-fonts-url))
         
         (default-directory project-root)

         (posts-rel (or posts iduh-org-ssg-posts-directory))
         (output-rel (or output iduh-org-ssg-output-directory))
         (layout (iduh-org-ssg--resolve-layout project-root skeleton))
         (skeleton-root (plist-get layout :skeleton-root))
         (templates-dir (plist-get layout :templates-dir))
         (static-dir (plist-get layout :static-dir))
         (_ (when (fboundp 'iduh-org-ssg-verify-skeleton)
              (iduh-org-ssg-verify-skeleton skeleton-root)))
         
         (posts-dir (expand-file-name posts-rel project-root))
         (output-dir (expand-file-name output-rel project-root))
         (iduh-org-ssg--templates-dir templates-dir)
         (generated-files '()))
    
    ;; Validate posts directory exists
    (unless (file-directory-p posts-dir)
      (iduh-org-mode-ssg--error 'iduh-org-mode-ssg-error
                      "Posts directory does not exist: %s" posts-dir))
    
    ;; Ensure output directory exists
    (unless (file-directory-p output-dir)
      (make-directory output-dir t))
    
    ;; Copy static assets to output directory
    (when (file-directory-p static-dir)
      (iduh-org-ssg--copy-directory-contents static-dir output-dir)
      (message "Copied static assets from %s" static-dir))
    
    ;; Process each org file
    (dolist (org-file (directory-files posts-dir t "\\.org$"))
      (condition-case err
          (let ((generated (iduh-org-ssg-generate-file org-file output-dir :skeleton skeleton-root)))
            (setq generated-files (cons generated generated-files)))
        (error
         (message "Error processing %s: %s" org-file (error-message-string err)))))
    
    ;; Report results
    (let ((count (length generated-files)))
      (message "Site build complete: %d file%s generated in %s"
               count
               (if (= count 1) "" "s")
               output-dir))
    
    (nreverse generated-files)))

;;;###autoload
;;;###autoload
(defun iduh-org-ssg-clean (&rest args)
  "Remove all generated files from the output directory.
Supports keyword arguments or a single string as the project base directory."
  (interactive)
  
  (let* ((all-args (if (and args (not (keywordp (car args))))
                       (cons :base args)
                     args))
         (base (plist-get all-args :base))
         (output (plist-get all-args :output))
         (iduh-org-ssg-output-directory (or output iduh-org-ssg-output-directory))
         (base-dir (expand-file-name (or base default-directory)))
         (output-dir (expand-file-name iduh-org-ssg-output-directory base-dir)))
    
    (when (file-directory-p output-dir)
      (when (yes-or-no-p (format "Delete all contents of %s? " output-dir))
        (delete-directory output-dir t)
        (message "Cleaned output directory: %s" output-dir)))))

;;;###autoload
(defun iduh-org-mode-ssg-generate-interactive ()
  "Interactively generate HTML from an Org file."
  (interactive)
  (call-interactively #'iduh-org-mode-ssg-generate))

;;;###autoload
;;;###autoload
(cl-defun iduh-org-mode-ssg-preview (input-file &key skeleton)
  "Generate and preview HTML from INPUT-FILE in browser.

Uses `iduh-org-ssg-skeleton-directory' (or SKELETON when provided) for
templates/static assets."
  (interactive
   (list (read-file-name "Input Org file: " nil nil t nil
                         (lambda (f) (or (file-directory-p f)
                                          (string-suffix-p ".org" f))))))
  (let* ((layout (iduh-org-ssg--resolve-layout default-directory skeleton))
         (skeleton-root (plist-get layout :skeleton-root))
         (iduh-org-ssg--templates-dir (plist-get layout :templates-dir))
         (static-dir (plist-get layout :static-dir))
         (_ (when (fboundp 'iduh-org-ssg-verify-skeleton)
              (iduh-org-ssg-verify-skeleton skeleton-root)))
         (temp-html (make-temp-file "iduh-org-mode-ssg-preview-" nil ".html"))
         (temp-dir (file-name-directory temp-html)))
    ;; Copy skeleton static assets into temp output.
    (when (file-directory-p static-dir)
      (iduh-org-ssg--copy-directory-contents static-dir temp-dir))
    ;; Generate HTML and open in browser.
    (let ((generated-file (iduh-org-ssg-generate-file input-file temp-dir :skeleton skeleton-root)))
      (browse-url-of-file generated-file))))

(provide 'iduh-org-mode-ssg)

;;; iduh-org-mode-ssg.el ends here
